---
  - name: Get GPG key for Docker
    become: true
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Add Docker repository
    become: true
    apt-repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
  - name: Update Cache
    become: true
    apt:
      update_cache: yes
  - name: Install Docker
    become: true
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io