---
- name: get gpg key for docker
  become: true
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: add docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: update cache
  become: true
  apt:
    update_cache: yes

- name: install docker
  become: true
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present